### ISSUE TITLE
Zeal doesn't open in Linux/Ubuntu

### ISSUE THREAD

**Issue by AnthonyWC** [gdelmas/IntelliJDashPlugin#68] opened 2017-12-09 23:02 UTC
Running latest Zeal v0.4 + Plugin Version: 3.2.3 in Ubuntu 16.04 with Webstorm

**Comment by alireza6677** [comment] 2017-12-13 05:01
I have the same problem in Arch linux with PyCharm.

**Comment by gdelmas** [comment] 2017-12-13 18:28
i currently have no linux desktop system setup to test. can you please try if the following command opens zeal from the command line:

    zeal --query test

or just

    zeal

**Comment by alireza6677** [comment] 2017-12-13 20:53
The `zeal --query test` gives this error:

![screenshot from 2017-12-14 00-22-10](https://user-images.githubusercontent.com/6321734/33961883-dad40ec8-e064-11e7-84ae-b67bc93ceafe.png)

but it seems like `zeal test` is working fine:

![screenshot from 2017-12-14 00-21-32](https://user-images.githubusercontent.com/6321734/33961920-fbab3ea0-e064-11e7-8f39-194fe18c9e31.png)

**Comment by gdelmas** [comment] 2017-12-13 23:29
looks like a zeal bug. can you please open an issue on its tracker and link it to this issue.

**Comment by gdelmas** [comment] 2017-12-14 00:33
i see zeal changed some time ago. will try to fix.

duplicate of #54

**Closed by gdelmas** 2017-12-14 00:33 UTC
Labels: duplicate

**Comment by AnthonyWC** [comment] 2017-12-15 05:29
Confirmed that it's working /w v3.2.5 Dash plugin.

**Comment by alireza6677** [comment] 2017-12-15 09:55
version 3.2.5 does not work for me. had to remove `--query` from code and recompile the extension to make it work.

**Comment by gdelmas** [comment] 2017-12-15 13:20
@alireza6677 where did you remove `--query` from code in 3.2.5? it shouldn't be in there.

**Comment by alireza6677** [comment] 2017-12-15 13:50
@gdelmas Yes it wasn't there and it wasn't working. I downloaded an older version [fork](https://github.com/lheberlie/IntelliJDashPlugin) and changed the ZealLauncher.java, now it's working fine.

**Comment by gdelmas** [comment] 2017-12-15 14:02
@alireza6677 when did you modify the fork and built it?

i suspect there the uri scheme is not registered correctly by zeal. you can try to use the uri scheme manually to debug this issue.

**Comment by alireza6677** [comment] 2017-12-15 14:16
@gdelmas Yesterday. 

I tried a simple java app:

```java
Desktop desktop = Desktop.getDesktop();
URI uri = new URI("dash-plugin://keys=python&query=open");
desktop.browse(uri);
```

It opens up Zeal correctly. No idea why the extension doesn't work 🤔.

**Comment by gdelmas** [comment] 2017-12-15 14:21
interessting. can you try building the plugin with the following line inserted [here](https://github.com/gdelmas/IntelliJDashPlugin/blob/21fe246519b733724d16b57b808dfb4cad544bae/src/de/dreamlab/dash/launcher/DashPluginSchemeLauncher.java#L47):

    Notifications.Bus.notify(new Notification("Dash", "Dash: Debug ", uriStr, NotificationType.INFORMATION));

the ides event window should display the uri then

**Comment by alireza6677** [comment] 2017-12-15 14:37
```
Dash: Debug : dash-plugin://keys=java,javafx,grails,groovy,playjava,spring,cvj,processing,javadoc&query=String
```

The query is valid and it actually worked !! 
But it doesn't work when i install the extension from intelliJ repositories.

**Comment by gdelmas** [comment] 2017-12-15 14:53
thanks, for testing. it is getting complicated :)

- did you check if the repositories do not still have the old version `3.2.4` on?
- maybe there was an issue installing from the repo? you might try to uninstall the plugin and reinstall `3.2.5` from repo.
- does installing from [this](https://github.com/gdelmas/IntelliJDashPlugin/releases/download/3.2.5/Dash.jar) file work?

**Comment by alireza6677** [comment] 2017-12-15 15:06
* Repositories have the 3.2.5 version:

![screenshot from 2017-12-15 18-30-09](https://user-images.githubusercontent.com/6321734/34047594-0180414c-e1c6-11e7-9d64-5413c2ba50b0.png)

* Reinstalled and still does not work. just shows this:

![screenshot from 2017-12-15 18-32-08](https://user-images.githubusercontent.com/6321734/34047723-66730558-e1c6-11e7-9703-b719b503a5df.png)

* Installed the file and it works.

**Comment by alireza6677** [comment] 2017-12-15 15:22
I just removed all the IDE config files and reinstalled it. Then installed the extension. Seems to be working. Thanks !

Still no idea what was causing the problem.

**Comment by gdelmas** [comment] 2017-12-15 15:23
probably the old file was stuck in some cache. thank you for debugging.
